# Generated by Django 5.0.7 on 2024-08-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_access_token_alter_user_refresh_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user'},
        ),
    ]
