version: "3.1"

services:
  db:
    image: mysql:8.0.39
    container_name: notes_db
    environment:
      MYSQL_DATABASE: "notes"
      MYSQL_USER: "notes_user"
      MYSQL_PASSWORD: "notes_password"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_HOST: "127.0.0.1"
    ports:
      - "3306:3306"
    expose:
      - "3306"
