version: "3.7"

services:
  db:
    image: mysql:8.0
    container_name: notes_db
    environment:
      MYSQL_DATABASE: notes
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: 127.0.0.1
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
