# Generated by Django 5.0.7 on 2024-08-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'note'},
        ),
    ]
